src/audit/apps/auditor/urls.py
from django.urls import path

from .views import AnalyzingAjaxView, GetLatestNews

urlpatterns = [
    path('analyzing/', AnalyzingAjaxView.as_view(), name='analyzing_ajax'),
    path('getnews/', GetLatestNews.as_view(), name='getnews_ajax')
]

app_name = 'auditor'

src/audit/audit/urls.py
from django.contrib import admin
from django.urls import path, include

from core import urls as core_urls
from apps.auditor import urls as auditor_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auditor/', include((auditor_urls, 'auditor'),
         namespace='auditor'), name='auditor'),
    path('', include((core_urls, 'core'), namespace='core'), name='core'),
]

src/audit/core/urls.py
from django.urls import path
from .views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

src/audit/apps/auditor/models.py
from utils.loading import is_model_registered
from .abstract_models import (AbstractAnalyzer,
                              AbstractAnalyzerLog,
                              AbstractNews)

__all__ = []


if not is_model_registered('auditor', 'Analyzer'):
    class Analyzer(AbstractAnalyzer):
        pass

    __all__.append('Analyzer')


if not is_model_registered('auditor', 'AnalyzerLog'):
    class AnalyzerLog(AbstractAnalyzerLog):
        pass

    __all__.append('AnalyzerLog')


if not is_model_registered('auditor', 'News'):
    class News(AbstractNews):
        pass

    __all__.append('News')

src/audit/apps/auditor/views.py
from django.views import View
from django.http.response import JsonResponse

from apps.auditor.libs import analyzer, scraper


class AnalyzingAjaxView(View):
    context = {
        'output': None,
        'word_count': 0,
        'internal_link_count': 0,
        'keywords': [],
        'title': None,
        'description': None,
        'warnings': [],
    }

    def post(self, request, *agrs, **kwargs):
        url = request.POST.get('url')

        output = analyzer.run(url)
        self.context.update({'output': output})

        if 'pages' in output:
            page = output['pages'][0]
            word_count = page.get('word_count', 0)
            keywords = page.get('keywords', [])
            title = page.get('title', None)
            description = page.get('description', None)
            warnings = page.get('warnings', [])

            self.context.update({
                'word_count': word_count,
                'internal_link_count': len(output['pages']),
                'keywords': keywords,
                'title': title,
                'description': description,
                'warnings': warnings,
            })

        return JsonResponse(self.context)


class GetLatestNews(View):
    context = {}

    def get(self, request, *agrs, **kwargs):
        source = request.GET.get('source')
        if source == 'cnn':
            results = scraper.get_latest_cnn_news()
            self.context.update({'results': results})
        return JsonResponse(self.context)

src/audit/core/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    context = {}
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, context=self.context)

src/audit/apps/auditor/templates/auditor/analyzing-form.html
<div class="mt-5 p-4 bg-white rounded-2">
	<form id="analyzing-form" method="POST" action="{% url 'auditor:analyzing_ajax' %}">
		{% csrf_token %}
		<div class="d-flex w-full">
			<input type="url" name="url" class="form-control flex-none w-100" placeholder="Example.com">
			<div class="ml-auto ps-3">
				<button type="submit" class="btn btn-info text-uppercase px-4 text-white">Audit</button>
			</div>
		</div>
	</form>
</div>

<div id="analyzing-result" class="mt-5">
	<div id="loading" class="d-flex align-items-center fs-6 d-none">
		<strong>Analyzing please wait...</strong>
		<div class="spinner-border ms-auto" role="status" aria-hidden="true" style="width: 20px; height: 20px"></div>
	</div>

	<div id="result"></div>
</div>

src/audit/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="Muhammad Rahman">
		<meta name="generator" content="SEO Audit Tools">
		<title>SEO Audit Tools</title>

		<link rel="canonical" href="{{ request.build_absolute_uri }}">

		<link href="{% static 'vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendors/bootstrap/css/bootstrap-utilities.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendors/bootstrap/css/bootstrap-grid.min.css' %}" rel="stylesheet">

		<!-- Favicons -->
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
		<link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
		<link rel="mask-icon" href="{% static 'favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">

		<!-- Custom styles for this template -->
		<link href="{% static 'app/css/app.css' %}" rel="stylesheet">
	</head>
  	<body>
		<main>
			{% include 'shared/navbar.html' %}
			{% block content %}{% endblock %}
			{% include 'shared/footer.html' %}
		</main>

		<script src="{% static 'vendors/jquery/js/jquery-3.7.0.min.js' %}"></script>
		<script src="{% static 'app/js/app.js' %}"></script>
		{% block js %}{% endblock %}
	</body>
</html>

src/audit/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container d-flex align-items-center">
	<div class="d-block mt-5 mb-5 pt-5 pb-5 w-100">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-md-8 col-lg-6 mx-auto">
				<div class="text-center">
					<h1 class="fw-bold mb-2">SEO Audit Tool</h1>
					<h3 class="fs-6 fw-normal">Enter an URL address and get a Free Website Analysis!</h3>
				</div>

				{% include 'auditor/analyzing-form.html' %}
			</div>
		</div>
	</div>
</div>
{% endblock %}